### ISSUE TITLE
doesnt work properly

### ISSUE THREAD

**Issue by gamingoninsulin** [rotolonico/Datapack-Converter#1]
C:\Users\Rondy\Desktop\Datapack-Converter-main>python.exe datapack_converter.py "C:\Users\Rondy\AppData\Roaming\.minecraft\saves\test2" 10 67 2 7 73 0 -d -n night_night-1.1
Writing datapack with the following chains at C:\Users\Rondy\AppData\Roaming\.minecraft\saves\test2\datapacks\night_night-1.1

- CHAIN r0
r0_0 | gamerule commandBlockOutput false

- CHAIN i0
i0_0 | scoreboard objectives add clock dummy "cycle"
i0_1 | scoreboard objectives setdisplay sidebar clock

- CHAIN r1
r1_0 | execute store result score time clock run time query daytime
r1_1 | execute if score time clock matches 18000 run gamerule doDaylightCycle false

- CHAIN r2
r2_0 | execute as @a at @s if data entity @s SleepingX run summon minecraft:tnt
Traceback (most recent call last):
  File "C:\Users\Rondy\Desktop\Datapack-Converter-main\datapack_converter.py", line 299, in <module>
    find_chains(blocks)
  File "C:\Users\Rondy\Desktop\Datapack-Converter-main\datapack_converter.py", line 153, in find_chains
    write_datapack(args.world_path, chains, "map_name" if args.n is None else args.n, args.f, args.d, all_blocks,
  File "C:\Users\Rondy\Desktop\Datapack-Converter-main\utils\datapack_writer.py", line 73, in write_datapack
    os.rename(os.path.join(datapack_path, "data", "converted_datapack"),
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Rondy\\AppData\\Roaming\\.minecraft\\saves\\test2\\datapacks\\night_night-1.1\\data\\converted_datapack' -> 'C:\\Users\\Rondy\\AppData\\Roaming\\.minecraft\\saves\\test2\\datapacks\\night_night-1.1\\data\\night_night-1.1'

**Comment by gamingoninsulin** [comment]
btw i use 1.19.3 is that an issue?

**Comment by Nik0-0** [comment]
"Cannot create a file when that file already exists:"
